name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    name: cargo check
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Check workspace
        run: PYO3_PYTHON=$(which python3.12) cargo check --workspace
